PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Controllers/IntergalacticDonationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using anyo_platform.Models;
using anyo_platform_core.Data;
using System.Security.Claims;
using anyo_platform_core.Data.ViewModels;
using System.Security.Policy;
using System.Text;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
namespace anyo_platform_core.Controllers
{
    [Authorize]
    public class IntergalacticDonationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public IntergalacticDonationsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> MicroServiceIndex()
        {
            string url = "https://localhost:7704/Donations/Get";
            using (HttpClient client = new HttpClient())
            {
                var json = await client.GetStringAsync(url);
                var apiModel = JsonConvert.DeserializeObject<DonationsViewModel>(json);
                if (apiModel == null)
                    return BadRequest();
                return View(apiModel);
            }
        }
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.IntergalacticDonation;
            var indexViewModel = new DonationsViewModel();
            foreach (var donation in applicationDbContext.ToList())
            {
                var model = new DonationViewModel()
                {
                    Message = donation.Message,
                    Id = donation.Id,
                    Quantity = donation.Quantity,
                    Mission = _context.IntergalacticMissions.FirstOrDefault(m => m.Id == donation.MissionId),
                    Package = _context.IntergalacticPackages.FirstOrDefault(m => m.Id == donation.PackageId),
                    DonorName = donation.DonorName
                };
                indexViewModel.Donations.Add(model);
            }
            return View(indexViewModel);
        }
        public IActionResult Create(int? id)
        {
            ViewData["DonorName"] = User.Identity.Name;
            ViewData["MissionId"] = id;
            ViewData["PackageId"] = new SelectList(_context.IntergalacticPackages, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> MicroserviceCreate([Bind("Message,Quantity,MissionId,DonorName,PackageId")] IntergalacticDonation intergalacticDonation)
        {
            if (ModelState.IsValid)
            {
                var url = "https://localhost:7704/Donations/Create";
                using (var client = new HttpClient())
                {
                    var json = JsonConvert.SerializeObject(intergalacticDonation);
                    var request = new HttpRequestMessage
                    {
                        Method = HttpMethod.Post,
                        RequestUri = new Uri(url),
                        Content = new StringContent(json, Encoding.UTF8, MediaTypeNames.Application.Json),
                    };
                    var response = await client.SendAsync(request);
                    return Ok();
                }
            }
            return BadRequest();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Message,Quantity,MissionId,DonorName,PackageId")] IntergalacticDonation intergalacticDonation)
        {
            if (ModelState.IsValid)
            {
                var mission = _context.IntergalacticMissions.Find(intergalacticDonation.MissionId);
                if (mission != null)
                {
                    mission.Current += intergalacticDonation.Quantity;
                }
                _context.Add(intergalacticDonation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DonorName"] = intergalacticDonation.DonorName;
            ViewData["MissionId"] = intergalacticDonation.MissionId;
            ViewData["PackageId"] = new SelectList(_context.IntergalacticPackages, "Id", "Name", intergalacticDonation.PackageId);
            return View(intergalacticDonation);
        }
        private bool IntergalacticDonationExists(int id)
        {
          return (_context.IntergalacticDonation?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Controllers/IntergalacticMissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using anyo_platform.Models;
using anyo_platform_core.Data;

namespace anyo_platform_core.Controllers
{
    public class IntergalacticMissionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IntergalacticMissionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.IntergalacticMissions.Include(i => i.Group);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.IntergalacticMissions == null)
            {
                return NotFound();
            }

            var intergalacticMissions = await _context.IntergalacticMissions
                .Include(i => i.Group)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (intergalacticMissions == null)
            {
                return NotFound();
            }

            intergalacticMissions.PackagesDonated = _context.IntergalacticDonation.Where(m => m.MissionId == intergalacticMissions.Id).ToList();

            return View(intergalacticMissions);
        }

        public IActionResult Create()
        {
            ViewData["GroupId"] = new SelectList(_context.IntergalacticGroups, "Id", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Banner,Status,Current,Target,GroupId")] IntergalacticMissions intergalacticMissions)
        {
            if (ModelState.IsValid)
            {
                _context.Add(intergalacticMissions);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GroupId"] = new SelectList(_context.IntergalacticGroups, "Id", "Name", intergalacticMissions.GroupId);
            return View(intergalacticMissions);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.IntergalacticMissions == null)
            {
                return NotFound();
            }

            var intergalacticMissions = await _context.IntergalacticMissions.FindAsync(id);
            if (intergalacticMissions == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = new SelectList(_context.IntergalacticGroups, "Id", "Name", intergalacticMissions.GroupId);
            return View(intergalacticMissions);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Banner,Status,Current,Target,GroupId")] IntergalacticMissions intergalacticMissions)
        {
            if (id != intergalacticMissions.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(intergalacticMissions);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IntergalacticMissionsExists(intergalacticMissions.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GroupId"] = new SelectList(_context.IntergalacticGroups, "Id", "Name", intergalacticMissions.GroupId);
            return View(intergalacticMissions);
        }

        // GET: IntergalacticMissions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.IntergalacticMissions == null)
            {
                return NotFound();
            }

            var intergalacticMissions = await _context.IntergalacticMissions
                .Include(i => i.Group)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (intergalacticMissions == null)
            {
                return NotFound();
            }

            return View(intergalacticMissions);
        }

        // POST: IntergalacticMissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.IntergalacticMissions == null)
            {
                return Problem("Entity set 'ApplicationDbContext.IntergalacticMissions'  is null.");
            }

            var intergalacticMissions = await _context.IntergalacticMissions.FindAsync(id);
            if (intergalacticMissions != null)
            {
                _context.IntergalacticMissions.Remove(intergalacticMissions);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IntergalacticMissionsExists(int id)
        {
          return (_context.IntergalacticMissions?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticMissions/Create.cshtml
@using anyo_platform.Models;
@model anyo_platform.Models.IntergalacticMissions

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}

<h1>Create</h1>

<h4>IntergalacticMissions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Banner" class="control-label"></label>
                <input asp-for="Banner" class="form-control" />
                <span asp-validation-for="Banner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="Html.GetEnumSelectList<MissionStatus>()" class="form-control"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Current" class="control-label"></label>
                <input asp-for="Current" class="form-control" />
                <span asp-validation-for="Current" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Target" class="control-label"></label>
                <input asp-for="Target" class="form-control" />
                <span asp-validation-for="Target" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <select asp-for="GroupId" class ="form-control" asp-items="ViewBag.GroupId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticMissions/Delete.cshtml
@model anyo_platform.Models.IntergalacticMissions

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IntergalacticMissions</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Banner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Banner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Current)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Current)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Target)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Target)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticMissions/Details.cshtml
@model anyo_platform.Models.IntergalacticMissions

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<h1>@Model.Name</h1>

<p>
    @Model.Description
</p>

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Banner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Banner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Current)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Current)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Target)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Target)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group.Name)
        </dd>
    </dl>

    <h1>Donations</h1>
    <hr />

    <table class="table">
        <thead>
            <tr>
                <th>
                    Message
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Donor
                </th>
                <th>
                    Package
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PackagesDonated)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Message)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DonorName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PackageId)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticMissions/Edit.cshtml
@using anyo_platform.Models;
@model anyo_platform.Models.IntergalacticMissions

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout";
}

<h1>Edit</h1>

<h4>IntergalacticMissions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Banner" class="control-label"></label>
                <input asp-for="Banner" class="form-control" />
                <span asp-validation-for="Banner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="Html.GetEnumSelectList<MissionStatus>()" class="form-control"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Current" class="control-label"></label>
                <input asp-for="Current" class="form-control" />
                <span asp-validation-for="Current" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Target" class="control-label"></label>
                <input asp-for="Target" class="form-control" />
                <span asp-validation-for="Target" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <select asp-for="GroupId" class="form-control" asp-items="ViewBag.GroupId"></select>
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticMissions/Index.cshtml
@model IEnumerable<anyo_platform.Models.IntergalacticMissions>

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Banner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Current)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Target)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Group)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) 
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Banner)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Current)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Target)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Create" asp-controller="IntergalacticDonations" asp-route-id="@item.Id">Donate</a>
            </td>
        </tr>
}
    </tbody>
</table>