PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Controllers/IntergalacticGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using anyo_platform.Models;
using anyo_platform_core.Data;

namespace anyo_platform_core.Controllers
{
    public class IntergalacticGroupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IntergalacticGroupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: IntergalacticGroups
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.IntergalacticGroups.Include(i => i.Leader);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: IntergalacticGroups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.IntergalacticGroups == null)
            {
                return NotFound();
            }

            var intergalacticGroup = await _context.IntergalacticGroups
                .Include(i => i.Leader)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (intergalacticGroup == null)
            {
                return NotFound();
            }

            return View(intergalacticGroup);
        }

        // GET: IntergalacticGroups/Create
        public IActionResult Create()
        {
            ViewData["LeaderId"] = new SelectList(_context.Users, "Id", "UserName");
            return View();
        }

        // POST: IntergalacticGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,About,HomePlanet,Logo,LeaderId")] IntergalacticGroup intergalacticGroup)
        {
            if (ModelState.IsValid)
            {
                _context.Add(intergalacticGroup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LeaderId"] = new SelectList(_context.Users, "Id", "UserName", intergalacticGroup.LeaderId);
            return View(intergalacticGroup);
        }

        // GET: IntergalacticGroups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.IntergalacticGroups == null)
            {
                return NotFound();
            }

            var intergalacticGroup = await _context.IntergalacticGroups.FindAsync(id);
            if (intergalacticGroup == null)
            {
                return NotFound();
            }
            ViewData["LeaderId"] = new SelectList(_context.Users, "Id", "UserName", intergalacticGroup.LeaderId);
            return View(intergalacticGroup);
        }

        // POST: IntergalacticGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,About,HomePlanet,Logo,LeaderId")] IntergalacticGroup intergalacticGroup)
        {
            if (id != intergalacticGroup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(intergalacticGroup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IntergalacticGroupExists(intergalacticGroup.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LeaderId"] = new SelectList(_context.Users, "Id", "UserName", intergalacticGroup.LeaderId);
            return View(intergalacticGroup);
        }

        // GET: IntergalacticGroups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.IntergalacticGroups == null)
            {
                return NotFound();
            }

            var intergalacticGroup = await _context.IntergalacticGroups
                .Include(i => i.Leader)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (intergalacticGroup == null)
            {
                return NotFound();
            }

            return View(intergalacticGroup);
        }

        // POST: IntergalacticGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.IntergalacticGroups == null)
            {
                return Problem("Entity set 'ApplicationDbContext.IntergalacticGroup'  is null.");
            }

            var intergalacticGroup = await _context.IntergalacticGroups.FindAsync(id);
            if (intergalacticGroup != null)
            {
                _context.IntergalacticGroups.Remove(intergalacticGroup);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IntergalacticGroupExists(int id)
        {
            return (_context.IntergalacticGroups?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticGroups/Create.cshtml
@model anyo_platform.Models.IntergalacticGroup

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}

<h1>Create</h1>

<h4>IntergalacticGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <input asp-for="About" class="form-control" />
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomePlanet" class="control-label"></label>
                <input asp-for="HomePlanet" class="form-control" />
                <span asp-validation-for="HomePlanet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaderId" class="control-label"></label>
                <select asp-for="LeaderId" class ="form-control" asp-items="ViewBag.LeaderId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticGroups/Delete.cshtml
@model anyo_platform.Models.IntergalacticGroup

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IntergalacticGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.About)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HomePlanet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HomePlanet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Leader)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Leader.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticGroups/Details.cshtml
@model anyo_platform.Models.IntergalacticGroup

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<h1>Details</h1>

<div>
    <h4>IntergalacticGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.About)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HomePlanet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HomePlanet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Leader)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Leader.UserName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticGroups/Edit.cshtml
@model anyo_platform.Models.IntergalacticGroup

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout";
}

<h1>Edit</h1>

<h4>IntergalacticGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <input asp-for="About" class="form-control" />
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomePlanet" class="control-label"></label>
                <input asp-for="HomePlanet" class="form-control" />
                <span asp-validation-for="HomePlanet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaderId" class="control-label"></label>
                <select asp-for="LeaderId" class="form-control" asp-items="ViewBag.LeaderId"></select>
                <span asp-validation-for="LeaderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PART2/anyo-platform-src/anyo-modernized/anyo-platform-core/Views/IntergalacticGroups/Index.cshtml
@model IEnumerable<anyo_platform.Models.IntergalacticGroup>
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h1>Groups</h1>

<p>
    <a asp-controller="IntergalacticGroups" asp-action="Create">Create Group</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.About)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomePlanet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Logo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Leader)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) 
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.About)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HomePlanet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Logo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Leader.UserName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>